import { StaffMortgageInput, StaffMortgageOutput } from '../types';

export function calculateStaffMortgage(input: StaffMortgageInput): StaffMortgageOutput {
  const { basicSalary, spouseIncome, tenureYears, interestRate, equityPct,
            employeeAge, retirementAge, hasSpouse, isScaledUp, serviceYears, positionLevel } = input;

              // 1. Max monthly payment (50% of combined income)
                const totalIncome = hasSpouse && spouseIncome ? basicSalary + Math.min(spouseIncome, basicSalary) : basicSalary;
                  const maxMonthly = totalIncome * 0.5;

                    // 2. Max loan based on PV of annuity
                      const monthlyRate = interestRate / 100 / 12;
                        let totalMonths = tenureYears * 12;
                          
                            let maxLoanPV: number;
                              if (monthlyRate > 0) {
                                  maxLoanPV = maxMonthly * (1 - Math.pow(1 + monthlyRate, -totalMonths)) / monthlyRate;
                                    } else {
                                        maxLoanPV = maxMonthly * totalMonths;
                                          }

                                            // 3. Adjust tenure based on retirement (must leave 1 year buffer)
                                              const remainingYears = retirementAge - employeeAge;
                                                if (tenureYears > remainingYears - 1 && remainingYears > 1) {
                                                    totalMonths = (remainingYears - 1) * 12;
                                                        if (totalMonths < 12) {
                                                              return { maxLoan: 0, maxPropertyPrice: 0, maxMonthlyPayment: 0, totalMonths: 0, isEligible: false, tenureUsed: 0 };
                                                                  }
                                                                      maxLoanPV = maxMonthly * (1 - Math.pow(1 + monthlyRate, -totalMonths)) / monthlyRate;
                                                                        }

                                                                          // 4. Equity contribution
                                                                            const maxPropertyPrice = maxLoanPV / (1 - equityPct / 100);

                                                                              // 5. Scale-up repayment (if 5+ years service)
                                                                                let adjustedLoan = maxLoanPV;
                                                                                  if (isScaledUp && serviceYears >= 5) {
                                                                                      adjustedLoan *= 1.10; // Simplified 10% uplift
                                                                                        }

                                                                                          // 6. Eligibility by position and service years
                                                                                            let isEligible = true;
                                                                                              let minService = 1;
                                                                                                if (positionLevel === 'Professional') minService = 2;
                                                                                                  if (serviceYears < minService) isEligible = false;

                                                                                                    return {
                                                                                                        maxLoan: Math.round(adjustedLoan),
                                                                                                            maxPropertyPrice: Math.round(maxPropertyPrice),
                                                                                                                maxMonthlyPayment: Math.round(maxMonthly),
                                                                                                                    totalMonths,
                                                                                                                        isEligible,
                                                                                                                            tenureUsed: Math.ceil(totalMonths / 12),
                                                                                                                              };
                                                                                                                              }

                                                                                                                              export function calculateRESA(basicSalary: number, serviceYears: number, employeeAge: number, retirementAge: number) {
                                                                                                                                let limit, months, collateral;
                                                                                                                                  if (serviceYears < 1) { limit = basicSalary * 2; months = 12; collateral = 'Personal Guarantee Required'; }
                                                                                                                                    else if (serviceYears < 2) { limit = basicSalary * 4; months = 18; collateral = 'Personal Guarantee Required'; }
                                                                                                                                      else { limit = basicSalary * 6; months = 36; collateral = 'None (Interest Free)'; }

                                                                                                                                        const yearsToRetire = retirementAge - employeeAge;
                                                                                                                                          if (yearsToRetire <= 4) {
                                                                                                                                              months = (yearsToRetire - 1) * 12;
                                                                                                                                                  if (months < 0) return { limit: 0, months: 0, interest: 0, collateral: 'Must settle before retirement' };
                                                                                                                                                    }

                                                                                                                                                      return { limit: Math.round(limit), months, interest: 0, collateral };
                                                                                                                                                      }

                                                                                                                                                      export function calculateConsumerLoan(input: any) {
                                                                                                                                                        const { annualIncome, spouseIncome, propertyValue, tenureYears, interestRate, customerCategory, workExperience } = input;
                                                                                                                                                          
                                                                                                                                                            const margins: Record<string, { collateral: number; priceDiff: number }> = {
                                                                                                                                                                'Diaspora/FCY/Diplomat': { collateral: 0.90, priceDiff: 0.50 },
                                                                                                                                                                    'Self-Employed Professional': { collateral: 0.85, priceDiff: 0.30 },
                                                                                                                                                                        'Employed Professional': { collateral: 0.85, priceDiff: 0.30 },
                                                                                                                                                                            'Business Owner': { collateral: 0.75, priceDiff: 0.30 },
                                                                                                                                                                                'Executive': { collateral: 0.75, priceDiff: 0.30 },
                                                                                                                                                                                    'Other': { collateral: 0.70, priceDiff: 0.25 },
                                                                                                                                                                                      };
                                                                                                                                                                                        const margin = margins[customerCategory] || margins['Other'];

                                                                                                                                                                                          const totalIncome = annualIncome + (spouseIncome ? Math.min(spouseIncome, annualIncome) : 0);
                                                                                                                                                                                            const maxMonthly = totalIncome * 0.5;
                                                                                                                                                                                              const monthlyRate = interestRate / 100 / 12;
                                                                                                                                                                                                const totalMonths = tenureYears * 12;
                                                                                                                                                                                                  const maxLoanByIncome = monthlyRate > 0 ? maxMonthly * (1 - Math.pow(1 + monthlyRate, -totalMonths)) / monthlyRate : maxMonthly * totalMonths;
                                                                                                                                                                                                    const maxLoanByCollateral = propertyValue * margin.collateral;
                                                                                                                                                                                                      
                                                                                                                                                                                                        const finalLoan = Math.min(maxLoanByIncome, maxLoanByCollateral);
                                                                                                                                                                                                          const isEligible = workExperience >= 3 && finalLoan > 0;

                                                                                                                                                                                                            return {
                                                                                                                                                                                                                maxLoan: Math.round(finalLoan),
                                                                                                                                                                                                                    maxLoanByIncome: Math.round(maxLoanByIncome),
                                                                                                                                                                                                                        maxLoanByCollateral: Math.round(maxLoanByCollateral),
                                                                                                                                                                                                                            collateralMargin: margin.collateral * 100,
                                                                                                                                                                                                                                totalMonths,
                                                                                                                                                                                                                                    isEligible,
                                                                                                                                                                                                                                      };
                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                      export function calculateTermLoan(input: any) {
                                                                                                                                                                                                                                        const { loanAmount, interestRate, tenureYears, sector, subSector, isExport } = input;
                                                                                                                                                                                                                                          const bankContribution = getBankContribution(sector, subSector, isExport);
                                                                                                                                                                                                                                            const requiredEquity = loanAmount * (1 - bankContribution) / bankContribution;
                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                const monthlyRate = interestRate / 100 / 12;
                                                                                                                                                                                                                                                  const totalMonths = tenureYears * 12;
                                                                                                                                                                                                                                                    const monthlyPayment = monthlyRate > 0 ? loanAmount * monthlyRate * Math.pow(1 + monthlyRate, totalMonths) / (Math.pow(1 + monthlyRate, totalMonths) - 1) : loanAmount / totalMonths;

                                                                                                                                                                                                                                                      return {
                                                                                                                                                                                                                                                          bankContribution: bankContribution * 100,
                                                                                                                                                                                                                                                              requiredEquity: Math.round(requiredEquity),
                                                                                                                                                                                                                                                                  monthlyPayment: Math.round(monthlyPayment),
                                                                                                                                                                                                                                                                      totalMonths,
                                                                                                                                                                                                                                                                        };
                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                        function getBankContribution(sector: string, subSector: string, isExport: boolean): number {
                                                                                                                                                                                                                                                                          const map: Record<string, number> = {
                                                                                                                                                                                                                                                                              'Manufacturing_export': 0.80,
                                                                                                                                                                                                                                                                                  'Manufacturing': 0.70,
                                                                                                                                                                                                                                                                                      'Agriculture_export': 0.70,
                                                                                                                                                                                                                                                                                          'Agriculture': 0.60,
                                                                                                                                                                                                                                                                                              'Export/FCY': 0.70,
                                                                                                                                                                                                                                                                                                  'Transport_export': 0.70,
                                                                                                                                                                                                                                                                                                      'Transport': 0.60,
                                                                                                                                                                                                                                                                                                          'Health/Education': 0.70,
                                                                                                                                                                                                                                                                                                              'Real Estate': 0.60,
                                                                                                                                                                                                                                                                                                                  'Construction': 0.60,
                                                                                                                                                                                                                                                                                                                      'Mining': 0.50,
                                                                                                                                                                                                                                                                                                                        };
                                                                                                                                                                                                                                                                                                                          const key = isExport ? `${sector}_export` : sector;
                                                                                                                                                                                                                                                                                                                            return map[key] || 0.50;
                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                            export function calculateOverdraft(input: any) {
                                                                                                                                                                                                                                                                                                                              const { odLimit, annualTurnover, currentBalance, businessYears, collateralValue } = input;
                                                                                                                                                                                                                                                                                                                                const turnoverRatio = annualTurnover / odLimit;
                                                                                                                                                                                                                                                                                                                                  const minDebitBalancePct = (currentBalance / odLimit) * 100;

                                                                                                                                                                                                                                                                                                                                    let turnoverRating: string;
                                                                                                                                                                                                                                                                                                                                      if (turnoverRatio >= 4) turnoverRating = 'Excellent';
                                                                                                                                                                                                                                                                                                                                        else if (turnoverRatio >= 3) turnoverRating = 'Very Good';
                                                                                                                                                                                                                                                                                                                                          else if (turnoverRatio >= 2) turnoverRating = 'Satisfactory';
                                                                                                                                                                                                                                                                                                                                            else if (turnoverRatio >= 1) turnoverRating = 'Unsatisfactory';
                                                                                                                                                                                                                                                                                                                                              else turnoverRating = 'Poor';

                                                                                                                                                                                                                                                                                                                                                let balanceRating: string;
                                                                                                                                                                                                                                                                                                                                                  if (minDebitBalancePct > 4) balanceRating = 'Poor';
                                                                                                                                                                                                                                                                                                                                                    else if (minDebitBalancePct > 0) balanceRating = 'Unsatisfactory';
                                                                                                                                                                                                                                                                                                                                                      else balanceRating = 'Satisfactory to Excellent';

                                                                                                                                                                                                                                                                                                                                                        const isRenewable = turnoverRatio >= 2 && minDebitBalancePct <= 4 && minDebitBalancePct > 0 && collateralValue >= odLimit * 0.7;

                                                                                                                                                                                                                                                                                                                                                          return {
                                                                                                                                                                                                                                                                                                                                                              turnoverRatio,
                                                                                                                                                                                                                                                                                                                                                                  minDebitBalancePct,
                                                                                                                                                                                                                                                                                                                                                                      turnoverRating,
                                                                                                                                                                                                                                                                                                                                                                          balanceRating,
                                                                                                                                                                                                                                                                                                                                                                              isRenewable,
                                                                                                                                                                                                                                                                                                                                                                                };
                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                export function calculatePreShipment(input: any) {
                                                                                                                                                                                                                                                                                                                                                                                  const { facilityLimit, annualExport, exportYears, commodityType, advanceAmount } = input;
                                                                                                                                                                                                                                                                                                                                                                                    const margin = commodityType === 'Coffee' ? 0.90 : 0.80;
                                                                                                                                                                                                                                                                                                                                                                                      const maxAdvance = Math.min(annualExport * 0.5, facilityLimit * margin);
                                                                                                                                                                                                                                                                                                                                                                                        const finalAdvance = Math.min(advanceAmount || maxAdvance, annualExport);
                                                                                                                                                                                                                                                                                                                                                                                          const exportPerformanceRatio = annualExport / facilityLimit;

                                                                                                                                                                                                                                                                                                                                                                                            let renewalStatus: string;
                                                                                                                                                                                                                                                                                                                                                                                              if (exportPerformanceRatio >= 2) renewalStatus = 'Full Renewal - Excellent Performance';
                                                                                                                                                                                                                                                                                                                                                                                                else if (exportPerformanceRatio >= 1.75) renewalStatus = '10% Limit Reduction or 6-Month Renewal';
                                                                                                                                                                                                                                                                                                                                                                                                  else if (exportPerformanceRatio >= 1.5) renewalStatus = '15% Limit Reduction';
                                                                                                                                                                                                                                                                                                                                                                                                    else if (exportPerformanceRatio >= 1.25) renewalStatus = '20% Limit Reduction';
                                                                                                                                                                                                                                                                                                                                                                                                      else renewalStatus = 'Convert to Term Loan / Review Required';

                                                                                                                                                                                                                                                                                                                                                                                                        return {
                                                                                                                                                                                                                                                                                                                                                                                                            maxAdvance: Math.round(finalAdvance),
                                                                                                                                                                                                                                                                                                                                                                                                                margin: margin * 100,
                                                                                                                                                                                                                                                                                                                                                                                                                    exportPerformanceRatio,
                                                                                                                                                                                                                                                                                                                                                                                                                        renewalStatus,
                                                                                                                                                                                                                                                                                                                                                                                                                            isEligible: exportYears >= 0.5,
                                                                                                                                                                                                                                                                                                                                                                                                                              };
                                                                                                                                                                                                                                                                                                                                                                                                                              }