import { Outlet, NavLink, useNavigate } from 'react-router-dom';
import { useAuth } from '../../hooks/useAuth';
import { Menu, X, LogOut, Home, Users, FileText, BarChart, Briefcase } from 'lucide-react';
import { useState } from 'react';

const Layout = () => {
  const { user, logout } = useAuth();
    const navigate = useNavigate();
      const [mobileOpen, setMobileOpen] = useState(false);

        const navItems = [
            { to: '/dashboard', icon: Home, label: 'Dashboard' },
                { to: '/staff-mortgage', icon: Briefcase, label: 'Staff Mortgage' },
                    { to: '/staff-auto', icon: Briefcase, label: 'Staff Auto' },
                        { to: '/resa', icon: Briefcase, label: 'RESA' },
                            { to: '/consumer', icon: Briefcase, label: 'Consumer Loan' },
                                { to: '/term', icon: Briefcase, label: 'Term Loan' },
                                    { to: '/overdraft', icon: Briefcase, label: 'Overdraft' },
                                        { to: '/pre-shipment', icon: Briefcase, label: 'Pre-Shipment' },
                                            { to: '/collateral', icon: Briefcase, label: 'Collateral' },
                                                { to: '/risk-rating', icon: BarChart, label: 'Risk Rating' },
                                                    { to: '/classification', icon: BarChart, label: 'Classification' },
                                                        { to: '/customers', icon: Users, label: 'Customers' },
                                                            { to: '/reports', icon: FileText, label: 'Reports' },
                                                              ];

                                                                const handleLogout = () => {
                                                                    logout();
                                                                        navigate('/login');
                                                                          };

                                                                            return (
                                                                                <div className="min-h-screen bg-gray-50 flex">
                                                                                      {/* Sidebar */}
                                                                                            <aside className={`fixed inset-y-0 left-0 z-50 w-64 bg-primary-800 text-white transform transition-transform duration-300 ease-in-out ${mobileOpen ? 'translate-x-0' : '-translate-x-full'} lg:translate-x-0`}>
                                                                                                    <div className="flex items-center justify-between p-4 border-b border-primary-700">
                                                                                                              <span className="text-xl font-bold">Dashen Loan</span>
                                                                                                                        <button className="lg:hidden" onClick={() => setMobileOpen(false)}>
                                                                                                                                    <X size={24} />
                                                                                                                                              </button>
                                                                                                                                                      </div>
                                                                                                                                                              <nav className="p-4 space-y-1">
                                                                                                                                                                        {navItems.map((item) => (
                                                                                                                                                                                    <NavLink
                                                                                                                                                                                                  key={item.to}
                                                                                                                                                                                                                to={item.to}
                                                                                                                                                                                                                              className={({ isActive }) =>
                                                                                                                                                                                                                                              `flex items-center gap-3 px-3 py-2 rounded-lg transition-colors ${
                                                                                                                                                                                                                                                                isActive ? 'bg-primary-700' : 'hover:bg-primary-700/50'
                                                                                                                                                                                                                                                                                }`
                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                            onClick={() => setMobileOpen(false)}
                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                      <item.icon size={20} />
                                                                                                                                                                                                                                                                                                                                                    <span>{item.label}</span>
                                                                                                                                                                                                                                                                                                                                                                </NavLink>
                                                                                                                                                                                                                                                                                                                                                                          ))}
                                                                                                                                                                                                                                                                                                                                                                                    <button
                                                                                                                                                                                                                                                                                                                                                                                                onClick={handleLogout}
                                                                                                                                                                                                                                                                                                                                                                                                            className="flex items-center gap-3 px-3 py-2 rounded-lg hover:bg-red-600/50 w-full mt-4 transition-colors"
                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                  <LogOut size={20} />
                                                                                                                                                                                                                                                                                                                                                                                                                                              <span>Logout</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                </nav>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="absolute bottom-4 left-4 right-4 text-sm text-primary-300 border-t border-primary-700 pt-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p className="font-medium">{user?.fullName}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="text-xs">{user?.role} • {user?.branch || 'Head Office'}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </aside>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {/* Main Content */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="flex-1 lg:ml-64">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {/* Top Bar */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <header className="bg-white shadow-sm p-4 flex items-center justify-between lg:justify-end">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button className="lg:hidden" onClick={() => setMobileOpen(true)}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Menu size={24} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="flex items-center gap-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span className="text-sm text-gray-600 hidden sm:inline">Welcome, {user?.fullName}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button onClick={handleLogout} className="text-sm text-red-600 hover:text-red-800">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Logout
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </header>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {/* Page Content */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <main className="p-4 lg:p-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Outlet />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  export default Layout;