name = "dashen-loan-backend"
account_id = "REPLACE_WITH_YOUR_ACCOUNT_ID"
compatibility_date = "2026-07-15"
type = "webpack"
workers_dev = true

[build]
command = "npm install && npm run build"
upload = { format = "service-worker" }
