import { useEffect, useState } from 'react';
import { BarChart, Bar, XAxis, YAxis, Tooltip, PieChart, Pie, Cell, LineChart, Line, ResponsiveContainer } from 'recharts';
import api from '../services/api';
import KPICard from '../components/dashboard/KPICard';

const Dashboard = () => {
  const [summary, setSummary] = useState<any>(null);
    const [trend, setTrend] = useState<any[]>([]);
      const [loading, setLoading] = useState(true);

        useEffect(() => {
            const fetchData = async () => {
                  try {
                          const [summaryRes, trendRes] = await Promise.all([
                                    api.get('/reports/dashboard'),
                                              api.get('/reports/npl-trend'),
                                                      ]);
                                                              setSummary(summaryRes.data.data);
                                                                      setTrend(trendRes.data.data);
                                                                            } catch (err) {
                                                                                    console.error(err);
                                                                                          } finally {
                                                                                                  setLoading(false);
                                                                                                        }
                                                                                                            };
                                                                                                                fetchData();
                                                                                                                  }, []);

                                                                                                                    if (loading) {
                                                                                                                        return (
                                                                                                                              <div className="flex items-center justify-center h-64">
                                                                                                                                      <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary-600"></div>
                                                                                                                                            </div>
                                                                                                                                                );
                                                                                                                                                  }

                                                                                                                                                    const COLORS = ['#22c55e', '#eab308', '#f97316', '#ef4444', '#3b82f6', '#8b5cf6'];

                                                                                                                                                      return (
                                                                                                                                                          <div className="p-6">
                                                                                                                                                                <h1 className="text-3xl font-bold text-primary-800 mb-6">Loan Dashboard</h1>

                                                                                                                                                                      {/* KPI Cards */}
                                                                                                                                                                            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8">
                                                                                                                                                                                    <KPICard title="Total Portfolio" value={summary?.totalPortfolio || 0} prefix="ETB " />
                                                                                                                                                                                            <KPICard title="Active Loans" value={summary?.activeLoans || 0} />
                                                                                                                                                                                                    <KPICard title="NPL Ratio" value={summary?.nplRatio || 0} suffix="%" />
                                                                                                                                                                                                            <KPICard title="Top Risk Grade (A+/B+)" value={summary?.topGradesPct || 0} suffix="%" />
                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                        {/* Charts */}
                                                                                                                                                                                                                              <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 mb-8">
                                                                                                                                                                                                                                      <div className="card">
                                                                                                                                                                                                                                                <h2 className="text-lg font-semibold mb-4">Portfolio by Loan Type</h2>
                                                                                                                                                                                                                                                          <ResponsiveContainer width="100%" height={300}>
                                                                                                                                                                                                                                                                      <BarChart data={summary?.loanTypeDistribution || []}>
                                                                                                                                                                                                                                                                                    <XAxis dataKey="type" />
                                                                                                                                                                                                                                                                                                  <YAxis />
                                                                                                                                                                                                                                                                                                                <Tooltip formatter={(v) => `${Number(v).toLocaleString()} ETB`} />
                                                                                                                                                                                                                                                                                                                              <Bar dataKey="amount" fill="#2563eb" />
                                                                                                                                                                                                                                                                                                                                          </BarChart>
                                                                                                                                                                                                                                                                                                                                                    </ResponsiveContainer>
                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                    <div className="card">
                                                                                                                                                                                                                                                                                                                                                                              <h2 className="text-lg font-semibold mb-4">Risk Distribution</h2>
                                                                                                                                                                                                                                                                                                                                                                                        <ResponsiveContainer width="100%" height={300}>
                                                                                                                                                                                                                                                                                                                                                                                                    <PieChart>
                                                                                                                                                                                                                                                                                                                                                                                                                  <Pie
                                                                                                                                                                                                                                                                                                                                                                                                                                  data={summary?.riskDistribution || []}
                                                                                                                                                                                                                                                                                                                                                                                                                                                  dataKey="count"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  nameKey="grade"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  cx="50%"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  cy="50%"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  outerRadius={100}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  label={(entry) => `${entry.grade}: ${entry.count}`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {(summary?.riskDistribution || []).map((_: any, index: number) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Cell key={index} fill={COLORS[index % COLORS.length]} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </Pie>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Tooltip />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </PieChart>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </ResponsiveContainer>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {/* NPL Trend */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="card">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <h2 className="text-lg font-semibold mb-4">NPL Trend (Last 12 Months)</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <ResponsiveContainer width="100%" height={250}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <LineChart data={trend}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <XAxis dataKey="month" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <YAxis domain={[0, 20]} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Tooltip formatter={(v) => `${v}%`} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Line type="monotone" dataKey="nplRate" stroke="#dc2626" strokeWidth={2} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </LineChart>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </ResponsiveContainer>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      export default Dashboard;