import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../hooks/useAuth';

const Login = () => {
  const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');
      const [error, setError] = useState('');
        const [loading, setLoading] = useState(false);
          const { login } = useAuth();
            const navigate = useNavigate();

              const handleSubmit = async (e: React.FormEvent) => {
                  e.preventDefault();
                      setError('');
                          setLoading(true);
                              try {
                                    await login(email, password);
                                          navigate('/dashboard');
                                              } catch (err: any) {
                                                    setError(err.message || 'Login failed');
                                                        } finally {
                                                              setLoading(false);
                                                                  }
                                                                    };

                                                                      return (
                                                                          <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-primary-600 to-primary-800 p-4">
                                                                                <div className="bg-white rounded-2xl shadow-2xl p-8 w-full max-w-md">
                                                                                        <div className="text-center mb-8">
                                                                                                  <h1 className="text-3xl font-bold text-primary-800">Dashen Bank</h1>
                                                                                                            <p className="text-gray-600 mt-2">Loan Processing System</p>
                                                                                                                    </div>
                                                                                                                            <form onSubmit={handleSubmit} className="space-y-6">
                                                                                                                                      {error && (
                                                                                                                                                  <div className="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded-lg text-sm">
                                                                                                                                                                {error}
                                                                                                                                                                            </div>
                                                                                                                                                                                      )}
                                                                                                                                                                                                <div>
                                                                                                                                                                                                            <label className="label">Email</label>
                                                                                                                                                                                                                        <input
                                                                                                                                                                                                                                      type="email"
                                                                                                                                                                                                                                                    value={email}
                                                                                                                                                                                                                                                                  onChange={(e) => setEmail(e.target.value)}
                                                                                                                                                                                                                                                                                className="input-field"
                                                                                                                                                                                                                                                                                              placeholder="Enter your email"
                                                                                                                                                                                                                                                                                                            required
                                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                            <div>
                                                                                                                                                                                                                                                                                                                                                        <label className="label">Password</label>
                                                                                                                                                                                                                                                                                                                                                                    <input
                                                                                                                                                                                                                                                                                                                                                                                  type="password"
                                                                                                                                                                                                                                                                                                                                                                                                value={password}
                                                                                                                                                                                                                                                                                                                                                                                                              onChange={(e) => setPassword(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                            className="input-field"
                                                                                                                                                                                                                                                                                                                                                                                                                                          placeholder="Enter your password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                        required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    type="submit"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                disabled={loading}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className="btn-primary w-full py-3 text-lg"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {loading ? 'Logging in...' : 'Sign In'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="text-center text-sm text-gray-500 mt-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Default: loan@dashen.com / password123
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          export default Login;