import { useState } from 'react';
import { useForm, SubmitHandler } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import api from '../services/api';
import Input from '../components/common/Input';
import Select from '../components/common/Select';
import Button from '../components/common/Button';
import Card from '../components/common/Card';

const schema = z.object({
  basicSalary: z.number().min(1, 'Required'),
    spouseIncome: z.number().optional(),
      loanAmountRequested: z.number().min(1, 'Required'),
        tenureYears: z.number().min(1).max(30),
          interestRate: z.number().min(0).max(30),
            equityPct: z.number().min(0).max(100),
              employeeAge: z.number().min(18).max(65),
                retirementAge: z.number().min(18).max(70),
                  hasSpouse: z.boolean(),
                    isScaledUp: z.boolean(),
                      serviceYears: z.number().min(0),
                        positionLevel: z.enum(['Director', 'Middle', 'Line', 'Professional']),
                        });

                        type FormData = z.infer<typeof schema>;

                        const StaffMortgage = () => {
                          const [result, setResult] = useState<any>(null);
                            const [loading, setLoading] = useState(false);
                              const { register, handleSubmit, watch, formState: { errors } } = useForm<FormData>({
                                  resolver: zodResolver(schema),
                                      defaultValues: {
                                            basicSalary: 50000,
                                                  spouseIncome: 0,
                                                        loanAmountRequested: 2000000,
                                                              tenureYears: 20,
                                                                    interestRate: 8,
                                                                          equityPct: 5,
                                                                                employeeAge: 30,
                                                                                      retirementAge: 60,
                                                                                            hasSpouse: false,
                                                                                                  isScaledUp: false,
                                                                                                        serviceYears: 5,
                                                                                                              positionLevel: 'Professional',
                                                                                                                  },
                                                                                                                    });

                                                                                                                      const hasSpouse = watch('hasSpouse');

                                                                                                                        const onSubmit: SubmitHandler<FormData> = async (data) => {
                                                                                                                            setLoading(true);
                                                                                                                                try {
                                                                                                                                      const response = await api.post('/loans/staff-mortgage', data);
                                                                                                                                            setResult(response.data.data);
                                                                                                                                                } catch (err: any) {
                                                                                                                                                      alert(err.response?.data?.error || 'Calculation failed');
                                                                                                                                                          } finally {
                                                                                                                                                                setLoading(false);
                                                                                                                                                                    }
                                                                                                                                                                      };

                                                                                                                                                                        return (
                                                                                                                                                                            <div className="max-w-6xl mx-auto p-6">
                                                                                                                                                                                  <h2 className="text-2xl font-bold text-primary-800 mb-6">Staff Mortgage Loan Calculator</h2>
                                                                                                                                                                                        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
                                                                                                                                                                                                <Card title="Loan Details">
                                                                                                                                                                                                          <form onSubmit={handleSubmit(onSubmit)} className="space-y-4">
                                                                                                                                                                                                                      <div className="grid grid-cols-2 gap-4">
                                                                                                                                                                                                                                    <Input label="Basic Salary" register={register} name="basicSalary" type="number" error={errors.basicSalary} />
                                                                                                                                                                                                                                                  {hasSpouse && (
                                                                                                                                                                                                                                                                  <Input label="Spouse Income" register={register} name="spouseIncome" type="number" error={errors.spouseIncome} />
                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                        <Input label="Loan Amount Requested" register={register} name="loanAmountRequested" type="number" error={errors.loanAmountRequested} />
                                                                                                                                                                                                                                                                                                                    <div className="grid grid-cols-3 gap-4">
                                                                                                                                                                                                                                                                                                                                  <Input label="Tenure (Years)" register={register} name="tenureYears" type="number" error={errors.tenureYears} />
                                                                                                                                                                                                                                                                                                                                                <Input label="Interest Rate (%)" register={register} name="interestRate" type="number" step="0.1" error={errors.interestRate} />
                                                                                                                                                                                                                                                                                                                                                              <Input label="Equity Contribution (%)" register={register} name="equityPct" type="number" error={errors.equityPct} />
                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                      <div className="grid grid-cols-2 gap-4">
                                                                                                                                                                                                                                                                                                                                                                                                    <Input label="Employee Age" register={register} name="employeeAge" type="number" error={errors.employeeAge} />
                                                                                                                                                                                                                                                                                                                                                                                                                  <Input label="Retirement Age" register={register} name="retirementAge" type="number" error={errors.retirementAge} />
                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="grid grid-cols-2 gap-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Input label="Service Years" register={register} name="serviceYears" type="number" error={errors.serviceYears} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Select
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      label="Position Level"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      register={register}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      name="positionLevel"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      options={['Director', 'Middle', 'Line', 'Professional']}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      error={errors.positionLevel}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="flex gap-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <label className="flex items-center gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <input type="checkbox" {...register('hasSpouse')} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Has Spouse
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <label className="flex items-center gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <input type="checkbox" {...register('isScaledUp')} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Scale-Up Repayment
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Button type="submit" loading={loading} fullWidth>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Calculate
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </Card>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {result && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Card title="Result">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="space-y-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="flex justify-between border-b pb-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span className="font-medium">Max Loan</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span className="text-green-600 font-bold">{result.maxLoan.toLocaleString()} ETB</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="flex justify-between border-b pb-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span className="font-medium">Max Property Price</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span className="text-primary-600 font-bold">{result.maxPropertyPrice.toLocaleString()} ETB</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="flex justify-between border-b pb-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span className="font-medium">Monthly Payment</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span className="font-bold">{result.maxMonthlyPayment.toLocaleString()} ETB</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="flex justify-between border-b pb-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span className="font-medium">Tenure</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span>{result.totalMonths} months ({result.tenureUsed} years)</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="flex justify-between pt-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span className="font-medium">Eligibility</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span className={result.isEligible ? 'text-green-600 font-bold' : 'text-red-600 font-bold'}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {result.isEligible ? '✅ Eligible' : '❌ Not Eligible'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </Card>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              export default StaffMortgage;